version: '3.7' # specify docker-compose version

services:
  bilibili-helper:
    build: .
    image: bilibili-helper:latest
    volumes:
      - ./logs:/bilibili-helper/logs
    # 按照 DEDEUSERID SESSDATA BILI_JCT SCKEY 的顺序填写
    command: DEDEUSERID SESSDATA BILI_JCT SCKEY